### PR TITLE
bugfix: Ensure event.data is a string or array of strings

### PR DESCRIPTION
**Pull request by pke**
The old code would crash with anything but a string set in `event.data`

### CODE REVIEW

**Comment by pke** [comment]
@andywer I propose this to make the code more robust against invalid input data.

However this PR is lacking tests. Since you have no unit tests for the server and the server code relying on `http` package `ServerResponse` etc I think the only solution would be to add a new endpoint to the server that is called from the client tests and that generate intentionally faulty event stream data.

Maybe we should also wrap `StreamContext.sendEvent` into `try/catch` and use `streamEvents` provided `onError` to report errors when the `event.data` is not `string|string[]`?

```js
const streamContext: StreamContext = {
  close: lowLevelStream.close,
  sendComment: lowLevelStream.sendComment,
  sendEvent(event) {
    try {
      lowLevelStream.sendMessage(event)
    } catch (error) {
      onError(error)
    }
  }
}
```

Maybe we can also try to use https://github.com/gcedo/eventsourcemock for unit testing the server code?

**Comment by andywer** [comment]
Failing with a more expressive error message seems like a good idea!

I don’t see the need to change testing here, though, as this PR contains no functional changes.

It already failed before when passing non-string data, I guess, and the proper error message is very nice to have, but doesn’t really justify any testing effort exceeding five lines of code or so 😉

**Comment by pke** [comment]
What about the `StreamContext.sendEvent` proposal I mentioned? It would not be part of this PR though.

**Comment by andywer** [comment]
What's the benefit of catching and calling `onError` over just throwing? The `onError` is just there to handle asynchronous errors if I'm not mistaken.

**Comment by andywer** [comment]
Ping 😉
@pke

**Comment by pke** [comment]
I'll check with the `onError` code again, but its not related to this PR anyway. You can merge at will ;)

**Pull request merged**
